.\"	$OpenBSD: mdoc.template,v 1.12 2010/09/04 08:00:15 jmc Exp $
.\"
.\" The following requests are required for all man pages.
.\"
.\" Remove `\&' from the line below.
.Dd $\&Mdocdate$
.Dt SHAFT 1
.Os
.Sh NAME
.Nm shaft
.Nd simple ipsec key manager with ssh
.Sh SYNOPSIS
.\" For a program:  program [-abc] file ...
.Nm shaft
.Op Fl abc
.Ar
.Sh DESCRIPTION
.Nm
is a simple IPsec tunnel negotiator implemented over ssh
.\" The following requests should be uncommented and used where appropriate.
.\" .Sh RETURN VALUES
.\" For sections 2, 3, and 9 function return values only.
.\" .Sh ENVIRONMENT
.\" For sections 1, 6, 7 & 8 only.
.\" .Sh FILES
.\" .Sh EXIT STATUS
.\" For sections 1, 6, & 8 only.
.\" .Sh EXAMPLES
.\" .Sh DIAGNOSTICS
.\" For sections 1, 4, 6, 7, and 8 only.
.\" .Sh ERRORS
.\" For sections 2, 3, and 9 error and signal handling only.
.\" .Sh SEE ALSO
.\" .Xr foobar 1
.\" .Sh STANDARDS
.\" .Sh HISTORY
.Sh AUTHORS
Mathieu Sauve-Frankel <msf@openbsd.org>
.\" .Sh CAVEATS
.\" .Sh BUGS
